### ISSUE TITLE
Hosts not working

### ISSUE THREAD

**Issue by niemant** [x0uid/SpotifyAdBlock#11]
Hello,
The audio ads are still working and there is a large ad at the bottom.
Regards.

**Comment by x0uid** [comment]
30 seconds Spotify premium ad? Those cant be stopped, are hard-coded into Spotify client. You need to modified client, also those ads are not tracking or collecting any data.

Got screenshot for the large ad at buttom?!

**Comment by niemant** [comment]
I was using another host file that blocked the audio ads, but it seems spotify updated, do you know where I can get the modified client you mention?
I'm attaching a screenshot in red you can see the ad I mention.
Regards.
![2020-03-30 12_08_03-](https://user-images.githubusercontent.com/20712470/77928842-4e66e280-727f-11ea-9cde-c20996288287.png)

**Comment by llacb47** [comment]
Try https://github.com/Xeroday/Spotify-Ad-Blocker/

**Comment by niemant** [comment]
> 
> 
> Try https://github.com/Xeroday/Spotify-Ad-Blocker/

last Updated 2 years ago...

**Comment by x0uid** [comment]
> I was using another host file that blocked the audio ads, but it seems spotify updated, do you know where I can get the modified client you mention?
> I'm attaching a screenshot in red you can see the ad I mention.
> Regards.
> ![2020-03-30 12_08_03-](https://user-images.githubusercontent.com/20712470/77928842-4e66e280-727f-11ea-9cde-c20996288287.png)

U cant block that because it hard-coded into client. You need to block wg.spotify.com to block that empty banner window. Its not functional banner anyway, at least its not collecting any info from client.

I don't know where you can get modified Spotify client, because its illegal to do so. You can pay for subscription of ignore 30 secs advertising every 10 minutes. At least i've blocked spy part of the client.
